<?php echo $this->doctype() ?>
<html>
<head>
<?php $this->headLink()->prependStylesheet('/css/default/page/style.css') ?>
<?php $this->headLink()->prependStylesheet('/css/default/page/errorstyle.css') ?>
<?php $this->headScript()->prependFile('/js/general.js'); ?>
<?php $this->headScript()->prependFile('/js/jquery-1.7.min.js'); ?>

<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() ?>

<?php echo $this->headLink() ?>
<?php echo $this->headStyle() ?>

<?php echo $this->headScript() ?>
</head>

<body lang="en">
<div class="mainContainer">
	<div class="contentContainer">
	<?php echo $this->layout()->content; ?>
	<?php echo $this->inlineScript() ?>
	</div>
</div>
</body>
</html>